# --- PARÂMETROS CAMERA --- 
VIDEO_PATH = "video/teste.mp4"
CAM_WIDTH = 320
CAM_HEIGHT = 320

# --- PARÂMETROS DO MODELO --- 
MODEL_PATH = "models/best_full_integer_quant.tflite"
CONFIDENCE_THRESHOLD = 0.5
DETECTION_INTERVAL = 1 # Processar todo frame (ou aumente para pular)

# --- PARÂMETROS DE ILUMINAÇÃO --- 
INITIAL_BRIGHTNESS = 0

# --- PARÂMETROS DE MOVIMENTO --- 
#SERVO
NEUTRAL_ANGLE = 95
MIN_ANGLE = 55
MAX_ANGLE = 135
FATOR_GIRO = 0.1
SERVO_INCREMENT = 5.0

#MOTOR
SPEED_INCREMENT = 10
MAX_SPEED = 255
MIN_SPEED = 100

# --- PID ---
KP = 25
KI = 0.0
KD = 8

# --- PARÂMETROS DE TRANSMISSÃO UDP ---
IP_RASP = "10.42.0.1" 
UDP_HOST = " 10.42.0.104" 
UDP_PORT = 9999 
JPEG_QUALITY = 80